<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup Label="Project">
    <TargetFramework>net8.0</TargetFramework>
    <OutputType>Library</OutputType>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <Description>click the circles. to the beat.</Description>
    <Authors>ppy Pty Ltd, GooGuTeam</Authors>
    <Copyright>Copyright (c) 2026 ppy Pty Ltd, GooGuTeam</Copyright>
    <PackageProjectUrl>https://github.com/GooGuTeam/osu</PackageProjectUrl>
    <RepositoryUrl>https://github.com/GooGuTeam/osu</RepositoryUrl>
    <PackageReleaseNotes>osu! (ruleset) modified by GooGuTeam.
Original copyright: Copyright (c) 2026 ppy Pty Ltd
Full license text: see LICENSE file</PackageReleaseNotes>
  </PropertyGroup>

  <PropertyGroup Label="Nuget">
    <Title>osu! (ruleset)</Title>
    <PackageId>g0v0.osu.Game.Rulesets.Osu</PackageId>
    <IsPackable>true</IsPackable>
  </PropertyGroup>

  <ItemGroup Label="Project References">
    <ProjectReference Include="..\osu.Game\osu.Game.csproj" />
  </ItemGroup>
</Project>
